WIP: better logs
hana3d/addon pull request #13
Opened 2020-11-26 20:15 UTC by naiane-yanachi-r2u

2020-11-26 21:11 UTC, fabio-nukui reviewed
Acho que está ficando bom!

Uma coisa que fiquei na dúvida é se os logs de subprocessos (rodados em arquivos "_bg" vão) vão funcionar com esse setup.

2020-11-26 21:11 UTC, fabio-nukui commented on ui.py
> +    def poll(cls, context):
Acho que não previsa ter esse `poll`. Esse método é usado para indicar para a UI que esse operator (botão) está ativo

2020-11-26 21:11 UTC, fabio-nukui commented on ui.py
> +class AppendInfo(Operator):
Acho melhor mover essa classe para o módulo logger. Esse módulo `ui.py` já está grande demais.

2020-11-26 21:11 UTC, fabio-nukui commented on logger.py
> +setup_logger()
Acho que ficaria mais legível se rodar esse `setup_logger` explicitamente no `__init__` do addon, já que é o único lugar que usa ele.

2020-11-26 21:11 UTC, fabio-nukui commented on ui.py
> +    bl_idname = f'{HANA3D_NAME}.info'
Acho melhor trocar o nome do operator.`bpy.ops.hana3d.info` parece genérico demais

2020-11-26 21:11 UTC, fabio-nukui commented on logger.py
> +
Acho que vale a pena ter mais um `FileHandler` que é criado/sobrescrito toda vez que o blender inicia (`mode='w'`), para ser usado em "error reports"

2020-11-26 21:11 UTC, fabio-nukui commented on src/preferences/profile.py
> +            logging.errpr(f'Failed to get profile data: {response.text}')  # noqa: WPS421
typo

2020-11-26 22:57 UTC, naiane-yanachi-r2u commented
> Uma coisa que fiquei na dúvida é se os logs de subprocessos (rodados em arquivos "_bg" vão) vão funcionar com esse setup.

Os logs nesses arquivos aparecem no console e no arquivo, mas não na ui do blender... Acho que desta forma está ok

2020-11-30 22:10 UTC, h7seiji commented on requirements.txt
> +isort==4.3.5
por que essas mudanças de versão?

2020-11-30 22:19 UTC, aviggiano commented on requirements.txt
> +isort==4.3.5
porque a versão anterior tava 'hardcodada' e incompatível com o wemake-python-standard
pensei em simplesmente atualizar

2020-11-30 22:40 UTC, h7seiji requested changes
Só levantei alguns pontos. Ficou muito bom.

2020-11-30 22:40 UTC, h7seiji commented on logger.py
> +    dir_path = os.path.join(os.getcwd(), 'hana3d_logs')
Se o blend não estiver salvo `os.getcwd()` vai retornar a pasta de instalação do Blender, que provavelmente no Windows vai esta no Program Files, então não vai ter permissão de escrita se não for executado como administrador.

2020-11-30 22:40 UTC, h7seiji commented on logger.py
> +    dir_path = os.path.join(os.getcwd(), 'hana3d_logs')
Acho que poderia salvar na pasta `hana3d_data` mesmo.

2020-11-30 22:40 UTC, h7seiji commented on logger.py
> +        bpy.utils.register_class(cl)
Faltou `unregister()`.

2020-11-30 22:40 UTC, h7seiji commented on __init__.py
> +logger.setup_logger()
Acho que isso ficaria melhor dentro do `register()`, só não sei se quebraria algo essa mudança, mas é algo minor de qualquer jeito, poderia ficar assim.

2020-11-30 22:43 UTC, h7seiji commented on requirements.txt
> +isort==4.3.5
entendi

2020-11-30 22:47 UTC, naiane-yanachi-r2u commented on __init__.py
> +logger.setup_logger()
dentro do `register()` não funciona

2020-12-01 00:18 UTC, naiane-yanachi-r2u commented
fiz algumas alterações no `logger.py` só para não adicionar um handler múltiplas vezes

2020-12-01 00:20 UTC, aviggiano commented on logger.py
> +                stage = re.match(r'.*(hana3d_.*)\\.*', record.pathname)
acho que vc pode pegar isso do próprio 

```python
from .config import HANA3D_NAME
_, stage = HANA3D_NAME.split('_')
```

2020-12-01 13:31 UTC, h7seiji approved these changes

2020-12-01 14:27 UTC, naiane-yanachi-r2u commented on logger.py
> +                stage = re.match(r'.*(hana3d_.*)\\.*', record.pathname)
Desse jeito não funciona, por isso mudei. Acontece que, quando você passa essa classe pro logger, ela fica "gravada", sendo que `record` é a única variável.

2020-12-01 14:28 UTC, merged